/* Presenter Q&A bank — press Q in presenter.html */
window.QA = [
  { tag: "Hardest part", q: "What was the hardest part of the Answer.AI project?",
    a: ["Saying no. All three directions were real, and two of them had louder internal champions — exam prep looked like fast revenue.",
        "My job was to turn the debate into evidence: the strategic-fit questions plus two-week probes, so the decision wasn't 'Bella's opinion' but 'what 20% of students actually did'.",
        "The second hard part was holding the line on the core. Everyone wanted new features; I kept arguing that if the explanation isn't clearly better, nothing on top of it matters.",
        "Takeaway: the hardest design work was framing the decision, not drawing the screens."] },
  { tag: "Reflection", q: "If you could redo it, what would you do differently?",
    a: ["Run the probes earlier and smaller. We spent weeks debating before we shipped anything — a two-week probe would have ended that argument in week one.",
        "Instrument the core loop before redesigning it. We had good top-line numbers but thin per-step data on where students dropped inside an answer.",
        "Bring the tutors' personalities in earlier. Reach turned out to matter for retention too, and we treated it as a later layer.",
        "And I'd write the goal sentence on day one: 'from solving one question to supporting how students learn every day' — everything got easier once that existed."] },
  { tag: "Influence", q: "How did you get the team to choose daily learning over exam prep?",
    a: ["I didn't argue taste against taste. I laid all three directions against four questions the CEO cared about: growth, existing users, right to win, and keeping college students.",
        "Then I proposed two lightweight probes so the loudest opinions could be checked with real behavior. The AP demo's 4% completion did more than any slide.",
        "I also made the trade-off explicit: exam prep would read as 'not for me' to two million college users. Naming the loss made the choice feel responsible, not conservative.",
        "Result: the decision was owned by the team, and design got a seat from strategy through shipping."] },
  { tag: "Collaboration", q: "Tell me about a disagreement with a PM or engineer and how you handled it.",
    a: ["At Wanaka, engineering wanted to keep all tools visible in the studio — 'power users need them'. I wanted the game scene uncovered and tools sorted by frequency.",
        "Instead of debating, I built the redesign as a working demo with Claude Code and we watched three new creators use both. They found the first game faster in the simpler one, and the power tools were still one click away under Create and Settings.",
        "We agreed on the trade-off in writing: fewer visible controls, faster first game, and a 'click anything to locate it' rule so nothing felt hidden.",
        "What I learned: a demo ends a disagreement faster than a deck."] },
  { tag: "Metrics", q: "How do you know a design decision worked?",
    a: ["I set the metric before the design, tied to the goal sentence. For Answer.AI it was 30-day retention and daily actives, not clicks on the new feature.",
        "Each layer had its own leading signal: follow-up questions for the core, deck creation for flashcards, next-day return for study rooms.",
        "I look at cohorts, not averages — students who built a deck in week one vs. those who didn't — so we know the feature caused it.",
        "And I still go to campus events. The report-card moment is the qualitative check that the numbers mean something."] },
  { tag: "AI workflow", q: "How do you use AI day to day — and where does it fail you?",
    a: ["It's in every step: research agents for direction, Claude Code + Figma on our design system to test feasibility, AI drafts for edge cases, motion and assets, a design-QA skill before review.",
        "Where it fails: taste and consistency. Left alone it drifts — wrong spacing, generic characters, inconsistent tone. That's why I write skills that encode our standards, and why key pages are still designed by hand.",
        "It also fails at judgment: it will happily build the wrong thing beautifully. The 'what' and 'why' stay with me.",
        "Rule of thumb: AI for volume and speed, me for decisions, details and specs."] },
  { tag: "Role", q: "Walk me through how you'd design a new effect from idea to launch.",
    a: ["Start from the formula: an instant hook, a playable loop, a shareable result, a social trigger. If an idea can't fill all four in one sentence, it's not ready.",
        "Prototype the loop first, ugly. With Effect House's visual scripting or a quick Claude Code build, I'd test the first second and the fail state on five people before touching the look.",
        "Then the look: the face, the end card, the caption-worthy frame — because that's what gets screenshotted and posted.",
        "Launch small with a challenge or a duet hook, watch shooting and remix rates for a week, and iterate on the fail moment — failing is content too."] },
  { tag: "JD skill", q: "How do you turn your visual standards and taste into reusable AI skills?",
    a: ["A skill is a written contract: what good looks like, what's forbidden, and examples. For Wanaka's game covers it's composition rules, palette, character framing, and seven reference pairs of good vs. bad.",
        "I write it, run it 20 times, mark the failures, and revise the rules until the failure rate is low enough for the team to use without me.",
        "Three are public: the game cover skill, the agent voice skill, and the design-QA skill engineers run before review.",
        "The mindset: if I'd correct it in a review, it belongs in the skill."] },
  { tag: "Motivation", q: "Why TikTok Effect House, and why now?",
    a: ["Play is where I started — kids' games at ABCmouse — and every product since has been gamified. Effects are the most playful surface on the internet.",
        "The role is exactly where I already work: game loops, AI-assisted creation, turning taste into skills, shipping playable prototypes.",
        "Scale is the draw. At Answer.AI a good decision reached seven million students; an effect can reach hundreds of millions of posts.",
        "And I genuinely enjoy the format — I went through the top creators page and couldn't stop trying them."] },
  { tag: "Cross-timezone", q: "How do you work with a team in China across time zones?",
    a: ["I've done it for two years — Answer.AI's engineers are in China, Wanaka's team is split between the US and China — so it's my normal, not an exception.",
        "The rule is: overlap is for decisions, the rest is async. New York evening is Beijing morning, so I keep one daily window there for reviews and anything that needs a real conversation.",
        "Everything else goes in writing that can be acted on without me: working demos instead of static mocks, a design-QA skill engineers run on their own, specs with the 'why' included so nobody waits eight hours to ask.",
        "And I over-communicate the state of things — a short end-of-day note on what's done, what's blocked, what I need by their morning. It sounds small, but it's what keeps a 12-hour gap from turning into a 24-hour delay.",
        "Being bilingual helps: I can read the room in Chinese and write the doc in English, so nothing gets lost in between."] },
  { tag: "0 → 1", q: "How do you work in a tiny team with a lot of ambiguity?",
    a: ["Write the rule before the roadmap. At Wanaka it was one sentence: people do what they love and are good at, AI does what it does best. Every feature decision checked against it.",
        "Ship working demos instead of documents — with three people, a demo is the spec, the alignment meeting and the user test at once.",
        "Sequence by pain: the three walls — code, art, game design — in the order creators hit them.",
        "And protect the core: I still design the key pages by hand, even when everything else is generated."] }
];
